### ISSUE TITLE
7bit coding split problem

### ISSUE THREAD

**Issue by shranet** [linxGnu/gosmpp#100]
The code:
https://github.com/linxGnu/gosmpp/blob/bcdfa263c5796aa0026c610360c8024d0755c27b/data/codings.go#L95-L97

Should be like this:
```go
func (c *gsm7bit) ShouldSplit(text string, octetLimit uint) (shouldSplit bool) {
	if c.packed {
		return uint((len(text)*7+7)/8) > octetLimit
	} else {
		return uint(len(text)) > octetLimit
	}
}
```

Because the string is 160 characters long, it doesn't split.

**Comment by linxGnu** [comment]
Thank you for pointing out the issue.
I made a fix and will release a new version soon.

**Comment by krstdmr** [comment]
@linxGnu I have some modifications here in the link down. In addition to the fix by @shranet here in ShouldSplit method, I believe the changes I have made down in the link is sufficient, otherwise it splits just after 140 characters even though that is GSM-7Bit **packed=true**. What do you think? If you agree with me I will create a pull request for my changes? I have tested and checked every single bit and the message size via WireShark and it seems like it works as expected and the size of the message is 140 for a 160-char length GSM-7 Bit packed=true tagged message.

https://github.com/linxGnu/gosmpp/compare/master...krstdmr:gosmpp:master

**Comment by krstdmr** [comment]
Thanks @linxGnu . Will do that in a few days.

**Comment by krstdmr** [comment]
@linxGnu here is the complete PR. It seems like I don't have a permission to assign any of those three above. I will just tag the names in PR. Thanks in advance.
https://github.com/linxGnu/gosmpp/pull/136
