### ISSUE TITLE
The problem of getting MessageID after Submit

### ISSUE THREAD

**Issue by YourksChan** [linxGnu/gosmpp#29]
transmitter, err := gosmpp.NewTransmitterSession()
transmitter.Transmitter().Submit()

type TransmitSettings struct {
	// WriteTimeout is timeout/deadline for submitting PDU.
	WriteTimeout time.Duration

	// EnquireLink periodically sends EnquireLink to SMSC.
	// The duration must not be smaller than 1 minute.
	//
	// Zero duration disables auto enquire link.
	EnquireLink time.Duration

	// OnSubmitError notifies fail-to-submit PDU with along error.
	OnSubmitError func(pdu.PDU, error)

	// OnRebindingError notifies error while rebinding.
	OnRebindingError func(error)

	// OnClosed notifies `closed` event due to State.
	OnClosed func(State)
}

I did n’t find any way to get Message. I need to get MessageID after submission and use it as a tag. I look forward to your answer. Thanks!

**Comment by linxGnu** [comment]
@YourksChan I think we could provide SuccessHook, same as `OnSubmitError`. You could get message id through `pdu.PDU`. 
You could then cast pdu.PDU to SubmitSM and get message id.
I wonder if that work for you?
kindly cc @bachhh

**Comment by YourksChan** [comment]
I hope to get pdu.PDU immediately after completion!
Because this will have a great impact on our project! thank you for your reply!

pdu, err := transmitter.Transmitter().Submit()

**Comment by bachhh** [comment]
Hi @YourksChan , if you want to get the Sequence Number of each PDU, you can custom assign for each one of them yourself.
If you want to get the MessageID, it is a tag string that you get from SMSC entity in a SubmitSMResp. Because SMPP is inherently an asynchronous protocol, you would need to cache your SubmitSM, and match it with SubmitSMResp later ( using Sequence Number ).

```
pdu, err := transmitter.Transmitter().Submit()
cache.Add(pdu.Header().SequenceNumber, pdu)

// Handle Submit SM Resp
p := cache.Get(submitSMResp.Header().SequenceNumber)
p.MessageID
```

I cannot support using `Transmitter.Submit()` as a synchronous request.

**Comment by YourksChan** [comment]
Yes, it's useful. Can you give me a complete case?

**Comment by linxGnu** [comment]
@YourksChan 
1. MessageID: in SubmitSMResp. After you submit a SMS to SMSC, SMSC will return it. It's async process that you could not expect when it happens.
2. SequenceNumber: in SubmitSM. You could specify your own sequence number instead of auto generated from gosmpp lib.

So, could you please tell me which one you need?

**Comment by YourksChan** [comment]
MessageID

Linh Tran Tuan <notifications@github.com> 于2020年5月31日周日 下午1:04写道：

**Comment by YourksChan** [comment]
MessageID

**Comment by linxGnu** [comment]
@YourksChan in case of MessageID, as I explained above, there is no way we could get it in sync pattern as you want. SMPP Protocol itself is async pattern.
Please get `MessageID` via following steps:
1. Save SequenceNumber in your cache. SequenceNumber is generated automatically or manually. SequenceNumber is considered SubmitSM ID in a session.
2. Receiving SubmitSMResp consists of SequenceNumber of previous SubmitSM and MessageID.

In this way, you could map and know your previous SubmitSM with later MessageID.

I will close this issue. Thank you for your concern.
