### ISSUE TITLE
Setting DCS explicitly 

### ISSUE THREAD

**Issue by arshabbir** [linxGnu/gosmpp#64]
I am trying to set the data coding scheme to 0xf6(246) to test SAT push messaging in a production environment. I couldn't find a way to provision the DCS explicitly for this. Could anyone please help here.. Thank you very much.

**Comment by goten4** [comment]
@arshabbir Thanks for the issue, it's actually a lack in the library.

For the moment, the library managed effectively the following data codings :
```
	GSM7BITCoding byte = 0x00
	ASCIICoding byte = 0x01
	BINARY8BIT1Coding byte = 0x02
	LATIN1Coding byte = 0x03
	BINARY8BIT2Coding byte = 0x04
	CYRILLICCoding byte = 0x06
	HEBREWCoding byte = 0x07
	UCS2Coding byte = 0x08
```

The datacodings 0xF? are not currently supported.
Here is what the specs says :
```
0xF0 : default SMS-C charset  / class 0
0xF1 : default SMS-C charset  / class 1
0xF2 : default SMS-C charset  / class 2
0xF3 : default SMS-C charset  / class 3
0xF4 : binary / class 0
0xF5 : binary / class 1
0xF6 : binary / class 2
0xF7 : binary / class 3
```

The problem is that we don't manage for the moment a default SMS-C charset.
I'm not sure how we should manage the class of the message in this case.
@bachhh @linxGnu : any idea ?

**Comment by linxGnu** [comment]
I think we could support user custom data coding. Something like:

```go
import "github.com/linxGnu/gosmpp/data"
...
// an example of custom coding, user could define his encoder/decoder here
type userEncDec struct{}

func (*userEncDec) Encode(str string) ([]byte, error) {
	return []byte(str), nil
}

func (*userEncDec) Decode(data []byte) (string, error) {
	return string(data), nil
}
...
var s ShortMessage
customCoding := data.NewCustomEncoding(246, &userEncDec{})
err := s.SetMessageDataWithEncoding([]byte{0x61, 0x62, 0x63}, customCoding)
```

**Comment by linxGnu** [comment]
I wonder if it satisfies your demand @arshabbir 

If yes, I think #65 is sufficient. PTAL @goten4 @bachhh
